name: example
description: An example package using a code generator enabling sum-types in Dart.
version: 0.1.0
repository: https://github.com/werediver/sum-types-dart
author: Raman Fedaseyeu <raman.fedaseyeu@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta:
  sum_types:
    path: ../sum_types

dev_dependencies:
  dependency_validator:
  sum_types_generator:
    path: ../sum_types_generator
  build_runner:
