name: sum_types
description: Annotations for a code generator enabling sum-types in Dart.
version: 0.1.0
repository: https://github.com/werediver/sum-types-dart
author: Raman Fedaseyeu <raman.fedaseyeu@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:

dev_dependencies:
  dependency_validator:
  test: ^1.6.0
